name: atomify
description: >
  An idiomatic Dart library for building web applications with a focus on simplicity and reactivity. 
version: 0.1.0+2
repository: https://github.com/bryanbill/atomify

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  cssify: ^0.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
