name: ui
description: Kitawi default UI package
version: 1.0.0
repository: https://github.com/bryanbill/ui

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  web: ^1.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
